language: node_js

node_js: 
  - "stable"
cache: 
  directories:
  - "node_modules"

before_script:
  - cd API
  - npm install coveralls@3.0.2 nyc@13.3.0 

script:
  - npm run coverage

notifications:
  - email: false